_commit: 23b81b3d1dfabc7584bd980a5d1de6071e076ccf
_src_path: /Users/johnlee/code/CON/orinoco-lite-template
project_slug: orinoco-site
project_name: Orinoco Lite Site
site_description: A site built with Orinoco Lite.
site_base_url: https://example.invalid/orinoco-site/
pr_previews: none
include_site_specific: false
pages_history_limit: 3
