name: Publish project Pages

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  pages:
    if: >-
      ${{
        github.repository != 'ORINOCO-Lite/orinoco-lite-template' &&
        (
          github.event_name == 'workflow_dispatch' ||
          github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        )
      }}
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: ORINOCO-Lite/orinoco-lite-dev/.github/workflows/orinoco-pages.yml@adc60ee3b64db65b5b8b167bcbb9e9e02acb8863
    with:
      source-ref: >-
        ${{ github.event_name == 'workflow_dispatch' &&
        github.event.repository.default_branch || github.sha }}
      pixi-version: v0.73.0
      workflow-repository: ORINOCO-Lite/orinoco-lite-dev
      workflow-sha: adc60ee3b64db65b5b8b167bcbb9e9e02acb8863
